services:
  app:
    container_name: genai_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/usr/workspace/app/src
      - pnpm_store:/pnpm/.pnpm-store
    command: sh -c "pnpm install && npx prisma generate && pnpm dev"

  postgres:
    container_name: genai_app_postgres
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=genaiapp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=genaiapp_db
    volumes:
      - 'genai_app_postgres_data:/bitnami/postgresql'

  redis:
    container_name: genai_app_redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'genai_app_redis_data:/bitnami/redis/data'

volumes:
  pnpm_store:
  genai_app_redis_data:
  genai_app_postgres_data:
