services:
  app:
    container_name: genai_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/usr/workspace/app/src
      - pnpm_store:/pnpm/.pnpm-store
    command: sh -c "pnpm migrate:dev && pnpm dev"
    depends_on:
      - postgres
      - redis
      - qdrant

  postgres:
    container_name: genai_app_postgres
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: genaiapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: genaiapp_db
    ports:
      - '5432:5432'
    volumes:
      - 'genai_app_postgres_data:/bitnami/postgresql'

  redis:
    container_name: genai_app_redis
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '6379:6379'
    volumes:
      - 'genai_app_redis_data:/bitnami/redis/data'

  qdrant:
    container_name: genai_app_vector_db
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    volumes:
      - 'genai_app_qdrant_data:/qdrant/storage'

volumes:
  pnpm_store:
  genai_app_redis_data:
  genai_app_postgres_data:
  genai_app_qdrant_data:
