services:
  app:
    container_name: genai_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      IS_DOCKER: true
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      REDIS_URL: ${REDIS_URL_DOCKER}
    volumes:
      - ./src:/usr/workspace/app/src
      - pnpm_store:/pnpm/.pnpm-store
    command: sh -c "pnpm install && node dynamic-url-config.js && npx prisma generate && pnpm dev"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: genai_app_postgres
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: genaiapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: genaiapp_db
    ports:
      - '5432:5432'
    volumes:
      - 'genai_app_postgres_data:/bitnami/postgresql'

  redis:
    container_name: genai_app_redis
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '6379:6379'
    volumes:
      - 'genai_app_redis_data:/bitnami/redis/data'

volumes:
  pnpm_store:
  genai_app_redis_data:
  genai_app_postgres_data:
